# Generated by Django 4.0.4 on 2023-04-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
