# Generated by Django 4.0.4 on 2023-04-23 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childdata', '0002_imagef'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagef',
        ),
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
    ]
