# Generated by Django 4.0.4 on 2023-04-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childdata', '0003_delete_imagef_remove_image_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('sname', models.CharField(max_length=25)),
                ('photo', models.CharField(max_length=25)),
                ('uname', models.CharField(max_length=25)),
                ('epass', models.CharField(max_length=25)),
                ('hname', models.CharField(max_length=25)),
                ('haddress', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=25)),
                ('nname', models.CharField(max_length=25)),
                ('nphoto', models.CharField(max_length=25)),
                ('nuname', models.CharField(max_length=25)),
                ('nepass', models.CharField(max_length=25)),
            ],
        ),
    ]
