# Generated by Django 4.0.4 on 2023-04-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childdata', '0004_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
