# Generated by Django 4.0.4 on 2023-04-24 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childdata', '0005_imagef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagef',
            name='caption',
        ),
    ]
