# Generated by Django 4.0.4 on 2023-04-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childdata', '0008_blog_alter_doctor_epass_alter_doctor_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='epass',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='haddress',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nepass',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nphoto',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='nuname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='sname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='uname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='parent',
            name='address',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='parent',
            name='cdob',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='parent',
            name='cname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='parent',
            name='epass',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='parent',
            name='fname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='parent',
            name='hname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='parent',
            name='mobile',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='parent',
            name='photo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='parent',
            name='uname',
            field=models.CharField(max_length=25),
        ),
    ]
