# Generated by Django 4.0.4 on 2023-05-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childdata', '0011_vaccine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
